language: r
cache: packages

addons:
  apt:
    packages:
      - libv8-dev
      - valgrind

before_install:
  - wget http://download.osgeo.org/gdal/2.1.0/gdal-2.1.0.tar.gz
  - tar zxf gdal-2.1.0.tar.gz
  - cd gdal-2.1.0
  - ./configure
  - make
  - sudo make install
  - cd
  - wget http://download.osgeo.org/proj/proj-4.9.3.tar.gz
  - tar zxvf proj-4.9.3.tar.gz
  - cd proj-4.9.3
  - ./configure
  - make
  - sudo make install
  - cd
  - wget http://download.osgeo.org/geos/geos-3.6.0.tar.bz2
  - tar -jxvf geos-3.6.0.tar.bz2
  - cd geos-3.6.0
  - ./configure
  - make
  - sudo make install
  - sudo ldconfig
  - geos-config --version
  - cd $TRAVIS_BUILD_DIR

sudo: required

warnings_are_errors: true

r_packages:
  - rgdal
  - rgeos
  - roxygen2
  - rmarkdown
  - tmap
